---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/michaljemala/hello-go
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
